[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "subtyping-app"
version = "0.0.0"
description = "Comparison of subtyping methods"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
"numpy", 
"pandas", 
"scipy", 
"matplotlib", 
"seaborn", 
"pytest", 
"firthmodels"]
authors = [{name = "George M. Kolodziejczyk", email = "georgemkhd@gmail.com"}]

[project.optional-dependencies]
dev = ["pytest", "flake8"]

[tool.setuptools]
package-dir = {"" = "src"}

[project.scripts]
caps = "caps:main"